---
output: github_document
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.path = "man/figures/README-",
  out.width = "100%"
)
```

# HMFGraph-Supplementary

All R packages that are required for reproducing the results in the repository:
```r
install.packages("devtools")
install.packages("Matrix")
install.packages("aricode")
install.packages("pulsar")
install.packages("huge")
install.packages("BDgraph")
install.packages("igraph")
install.packages("qgraph")
install.packages("microbenchmark")
install.packages("parallel")
install.packages("foreach")
install.packages("doSNOW")
install.packages("progress")
install.packages("BGGM")
install.packages("hdi")
install.packages("flare")
install.packages("rags2ridges")
install.packages("BiocManager")
install.packages("RColorBrewer")
BiocManager::install("phyloseq")
devtools::install_github("zdk123/SpiecEasi")
devtools::install_github("gleday/beam")
devtools::install_github("apatrone2/thav.glasso")
devtools::install_github("AapoKorhonen/HMFGraph")
```

# Guide 


All functions require the working directory to be the main directory (where this README lies). The files are designed such that the user does not need to edit any files. All results can be replicated by running each file once found in this repository. The directory "functions" include functions the are used in other files. All figures are presented in the directory "figures".


## Simulating datasets

## The main results


## Comparisons of credibel intervals

Credible interval comparisons and the figures depicting the comparisons are produced with files found from directory "CI_comparisons".

## FDR control

The file "FDR_control.R" in the directory "FDR_control" produces the results for investigating the FDR control. The results are save to the directory "FDR_control/results". The figure depicting the results can be produced with the r file "FDR_control_plot.R".

## Computation times

All R-files in the directory "time_comparisons" have to be run. The results are save to directories "p_100", "p_200", "p_300" and "p_400". The current results are run with CPU i7-11700f with 32 GB system memory. The results can be view with file "print_results_time_comparisons.R" in the directory "time_comparisons/print_results".


